logins:
    - key: SING_IN.NICKNAME
      name: { en: "Nickname", ru: "Никнейм" }
    - key: SING_IN.MSISDN
      name: { en: "Phone number", ru: "Номер телефона" }
    - key: SING_IN.EMAIL
      name: { en: "Email", ru: "Email" }
